version: "3.8"
services:
  api:
    build: ./docker/uvicorn
    restart: always
    tty: true
    expose:
      - 8000
    environment:
      CONTAINER_ID: ${HOSTNAME}
    volumes:
      - ./api:/usr/src/api
    networks:
      - my-network
networks:
  my-network:
    external: true
