version: "3.8"
services:
  api:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8000
    volumes:
      - ../../backend:/usr/src/api
    networks:
      - my-network
networks:
  my-network:
    external: true
