version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-latest}
    restart: always
    tty: true
    expose:
      - 8000
    environment:
      CONTAINER_ID: ${HOSTNAME}
      IMAGE_TAG: ${IMAGE_TAG:-latest-$(date '+%Y%m%d%H%M%S')}
    volumes:
      - ./api:/usr/src/api
    networks:
      - my-network
networks:
  my-network:
    external: true
