name: Django-app workflow
on: [push]
jobs:

  deploy:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - name: executing remote ssh commands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PSW }}
            script: |
              cd dev;
              git clone git@github.com:DobruyPK/fastapi-demo-10.git;
              sudo chmod o+w /home/admin/dev/fastapi-demo-10;
              sudo cp .env fastapi-demo-10/;
              cd fastapi-demo-10;
              sudo echo "COMMIT_NAME=$(date +'%Y_%m_%d_%H_%M_%S')__$(git log -1 --format=%s $GITHUB_SHA)" > /home/admin/dev/fastapi-demo-10/.env_name;
              docker-compose up -d;
              cd ~/dev/
              yes |sudo rm -r ~/dev/fastapi-demo-10;