name: Django-app workflow
on: [push]
jobs:

  deploy:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - name: executing remote ssh commands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PSW }}
            script: |
              cd dev;
              echo "COMMIT_NAME=$(date +'%Y-%m-%d %H:%M:%S')- $(git log -1 --format=%s $GITHUB_SHA)" > /home/admin/dev/.env_name;
              git clone git@github.com:DobruyPK/fastapi-demo-10.git;
              cp .env fastapi-demo-10/;
              cp .env_name fastapi-demo-10/
              cd fastapi-demo-10;
              docker-compose up -d;
              cd ~/dev/
              yes |sudo rm -r ~/dev/fastapi-demo-10;
              rm .env_name;
